In [41]:
import pandas as pd
import numpy as np

In [42]:
# SCORING CONSTANTS
PYD = 0.02
PTD = 3
INTE = 0
RYD = 0.05
RTD = 6
REC = 0
RECTE = 0
WYD = 0.05
WTD = 6
FL = 0

FG = 3.2
FGA = 0
XPT = 1

SACK = 1
DTD = 6
SAFETY = 2
DINT = 2
FR = 2
unique_scoring = True # Use given fpts for DST or calculate based on given parameters

In [43]:
# Source: https://github.com/alexjt28/FantasyFootballDataScience/blob/main/WebscrubWeeklyPoints.py

def fantasypros_qb_projections():
    url = "https://www.fantasypros.com/nfl/projections/qb.php?week=draft"
    html = pd.read_html(url, header=1)
    df = html[0]
    data = df.rename(columns={"YDS": "PYDS", "TDS": "PTDS", "YDS.1": "RYDS", "TDS.1": "RTDS"})
    data = data.drop(columns = ["FPTS", "ATT", "CMP", "ATT.1"], axis = 1)
    data[['Player', 'Team']] = data['Player'].str.rsplit(' ', n=1, expand=True)
    data["Position"] = "QB"
    return data

def fantasypros_rb_projections():
    url = "https://www.fantasypros.com/nfl/projections/rb.php?week=draft"
    html = pd.read_html(url, header=1)
    df = html[0]
    data = df.rename(columns={"YDS": "RYDS", "TDS": "RTDS", "YDS.1": "WYDS", "TDS.1": "WTDS"})
    data = data.drop(columns = ["FPTS", "ATT"], axis = 1)
    data[['Player', 'Team']] = data['Player'].str.rsplit(' ', n=1, expand=True)
    data["Position"] = "RB"
    return data

def fantasypros_wr_projections():
    url = "https://www.fantasypros.com/nfl/projections/wr.php?week=draft"
    html = pd.read_html(url, header=1)
    df = html[0]
    data = df.rename(columns={"YDS": "WYDS", "TDS": "WTDS", "YDS.1": "RYDS", "TDS.1": "RTDS"})
    data = data.drop(columns = ["FPTS", "ATT"], axis = 1)
    data[['Player', 'Team']] = data['Player'].str.rsplit(' ', n=1, expand=True)
    data["Position"] = "WR"
    return data

def fantasypros_te_projections():
    url = "https://www.fantasypros.com/nfl/projections/te.php?week=draft"
    html = pd.read_html(url, header=1)
    df = html[0]
    data = df.rename(columns={"YDS": "WYDS", "TDS": "WTDS"})
    data = data.drop(columns = ["FPTS"], axis = 1)
    data[['Player', 'Team']] = data['Player'].str.rsplit(' ', n=1, expand=True)
    data["Position"] = "TE"
    return data

def fantasypros_k_projections():
    url = "https://www.fantasypros.com/nfl/projections/k.php?week=draft"
    html = pd.read_html(url, header=0)
    df = html[0]
    data = df.drop(columns = ["FPTS"], axis = 1)
    data[['Player', 'Team']] = data['Player'].str.rsplit(' ', n=1, expand=True)
    data["Position"] = "K"
    return data

def fantasypros_dst_projections():
    url = "https://www.fantasypros.com/nfl/projections/dst.php?week=draft"
    html = pd.read_html(url, header=0)
    df = html[0]
    data = df.rename(columns={"INT": "DINT", "TD": "DTD", "SAFETY": "SFT"})
    data = data.drop(columns = ["FF", "PA", "YDS AGN"], axis = 1)
    
    data["Team"] = None
    data["Position"] = "DEF"
    return data

In [44]:
qb = fantasypros_qb_projections()
qb["Points"] = PYD * qb["PYDS"] + PTD * qb['PTDS'] + INTE * qb['INTS'] + RYD * qb["RYDS"] + RTD * qb['RTDS'] + FL * qb['FL']
qb_streamlined = qb[["Player", "Position", "Team", "Points"]]
qb_streamlined

                      Player Position Team   Points
0                 Josh Allen       QB  BUF  345.554
1                Jalen Hurts       QB  PHI  340.208
2              Lamar Jackson       QB  BAL  320.654
3         Patrick Mahomes II       QB   KC  324.960
4         Anthony Richardson       QB  IND  289.374
..                       ...      ...  ...      ...
81               Sam Hartman       QB  WAS    8.560
82  Dorian Thompson-Robinson       QB  CLE    7.110
83              Tanner McKee       QB  PHI    8.240
84              Sam Ehlinger       QB  IND    8.160
85               Devin Leary       QB  BAL    1.300

[86 rows x 4 columns]

In [45]:
rb = fantasypros_rb_projections()
rb["Points"] = RYD * rb["RYDS"] + RTD * rb['RTDS'] + REC * rb['REC'] + WYD * rb["WYDS"] + WTD * rb['WTDS'] + FL * rb['FL']
rb_streamlined = rb[["Player", "Position", "Team", "Points"]]
rb_streamlined

                  Player Position Team   Points
0    Christian McCaffrey       RB   SF  281.902
1            Breece Hall       RB  NYJ  237.536
2         Bijan Robinson       RB  ATL  235.912
3        Jonathan Taylor       RB  IND  212.810
4         Saquon Barkley       RB  PHI  215.616
..                   ...      ...  ...      ...
133      Keaontay Ingram       RB   KC    4.200
134         Myles Gaskin       RB  MIN    3.960
135             C.J. Ham       RB  MIN    4.706
136      La'Mical Perine       RB   GB    3.880
137   Tyrion Davis-Price       RB  PHI    2.100

[138 rows x 4 columns]

In [46]:
wr = fantasypros_wr_projections()
wr["Points"] = RYD * wr["RYDS"] + RTD * wr['RTDS'] + REC * wr['REC'] + WYD * wr["WYDS"] + WTD * wr['WTDS'] + FL * wr['FL']
wr_streamlined = wr[["Player", "Position", "Team", "Points"]]
wr_streamlined

                 Player Position Team   Points
0           CeeDee Lamb       WR  DAL  245.626
1           Tyreek Hill       WR  MIA  241.074
2         Ja'Marr Chase       WR  CIN  216.858
3      Justin Jefferson       WR  MIN  213.328
4     Amon-Ra St. Brown       WR  DET  215.884
..                  ...      ...  ...      ...
214    Trishton Jackson       WR  MIN    3.554
215  Kristian Wilkerson       WR   LV    3.350
216      DeAndre Carter       WR  CHI    3.160
217       David Sills V       WR  DEN    2.702
218       Byron Pringle       WR  WAS    3.142

[219 rows x 4 columns]

In [47]:
te = fantasypros_te_projections()
te["Points"] = RECTE * te['REC'] + WYD * te["WYDS"] + WTD * te['WTDS'] + FL * te['FL']
te_streamlined = te[["Player", "Position", "Team", "Points"]]
te_streamlined

                Player Position Team   Points
0         Travis Kelce       TE   KC  166.380
1          Sam LaPorta       TE  DET  160.662
2         Mark Andrews       TE  BAL  152.918
3        George Kittle       TE   SF  139.244
4         Trey McBride       TE  ARI  143.984
..                 ...      ...  ...      ...
112  Teagan Quitoriano       TE  HOU    3.992
113    Stephen Carlson       TE  CHI    3.752
114       Tommy Hudson       TE   NO    3.744
115        Jake Tonges       TE   SF    3.492
116    Mitchell Wilcox       TE   NE    3.652

[117 rows x 4 columns]

In [48]:
k = fantasypros_k_projections()
k["Points"] = XPT * k['XPT'] + FG * k["FG"] + FGA * k['FGA']
k_streamlined = k[["Player", "Position", "Team", "Points"]]
k_streamlined

              Player Position Team  Points
0       Younghoe Koo        K  ATL   142.4
1      Justin Tucker        K  BAL   137.2
2    Harrison Butker        K   KC   134.9
3     Brandon Aubrey        K  DAL   134.9
4       Jake Elliott        K  PHI   132.0
5        Jason Myers        K  SEA   128.3
6   Ka'imi Fairbairn        K  HOU   127.9
7     Cameron Dicker        K  LAC   128.3
8        Blake Grupe        K   NO   125.1
9      Greg Zuerlein        K  NYJ   124.7
10    Evan McPherson        K  CIN   124.4
11        Tyler Bass        K  BUF   122.4
12      Cairo Santos        K  CHI   124.6
13        Jake Moody        K   SF   123.1
14          Matt Gay        K  IND   122.7
15  Brayden Narveson        K   GB   121.3
16     Jason Sanders        K  MIA   121.5
17  Chase McLaughlin        K   TB   118.9
18       Matt Prater        K  ARI   117.2
19    Dustin Hopkins        K  CLE   117.4
20        Cam Little        K  JAC   115.8
21        Jake Bates        K  DET   116.1
22      Joshua Karty        K  LAR   114.6
23     Chris Boswell        K  PIT   110.7
24         Nick Folk        K  TEN   111.2
25          Wil Lutz        K  DEN   108.1
26    Daniel Carlson        K   LV   109.3
27     Will Reichard        K  MIN   103.4
28      Eddy Pineiro        K  CAR   102.7
29         Cade York        K  WAS   101.1
30       Graham Gano        K  NYG    99.6
31         Joey Slye        K   NE    91.7

In [49]:
dst = fantasypros_dst_projections()
if(unique_scoring):
    dst["Points"] = SACK * dst["SACK"] + DTD * dst["DTD"] + FR * dst["FR"] + DINT * dst["DINT"] + SAFETY * dst['SFT']
else:
    dst["Points"] = dst['FPTS']

dst_streamlined = dst[["Player", "Position", "Team", "Points"]]
dst_streamlined

                   Player Position  Team  Points
0          Dallas Cowboys      DEF  None   68.75
1        Baltimore Ravens      DEF  None   66.85
2           New York Jets      DEF  None   66.70
3     Philadelphia Eagles      DEF  None   63.85
4          Houston Texans      DEF  None   63.95
5      Kansas City Chiefs      DEF  None   64.30
6     Pittsburgh Steelers      DEF  None   63.85
7     San Francisco 49ers      DEF  None   63.90
8        Cleveland Browns      DEF  None   63.75
9           Buffalo Bills      DEF  None   62.50
10     Indianapolis Colts      DEF  None   62.20
11         Miami Dolphins      DEF  None   62.40
12     Cincinnati Bengals      DEF  None   61.05
13   Los Angeles Chargers      DEF  None   60.45
14   Jacksonville Jaguars      DEF  None   60.70
15      Green Bay Packers      DEF  None   59.85
16  Washington Commanders      DEF  None   58.95
17        Atlanta Falcons      DEF  None   60.05
18        New York Giants      DEF  None   59.50
19     New Orleans Saints      DEF  None   59.35
20       Seattle Seahawks      DEF  None   58.85
21   Tampa Bay Buccaneers      DEF  None   58.65
22      Las Vegas Raiders      DEF  None   59.75
23         Denver Broncos      DEF  None   58.65
24          Chicago Bears      DEF  None   58.05
25          Detroit Lions      DEF  None   57.15
26      Minnesota Vikings      DEF  None   55.75
27       Los Angeles Rams      DEF  None   56.05
28       Tennessee Titans      DEF  None   54.65
29      Arizona Cardinals      DEF  None   53.65
30   New England Patriots      DEF  None   52.85
31      Carolina Panthers      DEF  None   51.30

In [50]:
player_df = pd.concat([qb_streamlined, rb_streamlined, wr_streamlined, te_streamlined, k_streamlined, dst_streamlined], ignore_index=True)
player_df = player_df.sort_values(by='Points', ascending=False)
player_df["Points"] = player_df["Points"].round()
player_df = player_df.reset_index(drop=True)
player_df.to_csv('UnivDynasty2023.csv', index=False)